### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by gep13** [doggy8088/gitea-chocolatey#1]
@doggy8088 are you still in a position to maintain this package?  Looks like the latest published version of gitea is 1.9.2.  Can you push a new package version to chocolatey.org?

**Comment by doggy8088** [comment]
@gep13 Yes, I am. I already been updated to 1.9.2. Thanks for let me know. :)

**Comment by gep13** [comment]
That is great, thank you! Are you familiar with AU? The framework for automatically detecting and publishing Chocolatey packages? The build.ps1 that you have is very similarly, and I don’t think it would take much to convert.

**Comment by doggy8088** [comment]
I already setup CI/CD for this package. I just forgot to setup Trigger for CI. 😝

**Comment by gep13** [comment]
Ah, perfect! Thank you for getting back to me so quickly about this!
